### ISSUE TITLE
v6.0 roadmap

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#46]
使用划词翻译的用户越来越多，需求也越来越多，[v5.x](https://github.com/lmk123/crx-selection-translate/tree/5.x-master) 的程序结构已经不太容易维护了，我准备花时间再次重写划词翻译，即开发  v6.0。

v6.0 将实现以下目标：

 + 有完善的单元测试。这将很容易检查出代码的改动会不会影响程序的其它部分。
 + 使用 [Webpack](http://webpack.github.io/)、[es2015](https://babeljs.io/docs/learn-es2015/)、以基于模块的方式构建程序结构。
 + 使用 [Vue.js](http://vuejs.org/) 构建程序界面。
 + 将常用的功能分离出去单独维护。

需要注意的是，**v6.0 不会修复 bug 或添加新功能**，这一版本的主要目标是重组程序结构。

目前的进度：

 - [x] 将常用功能分离成多个子项目
 - [x] 基本功能（翻译、网页划词翻译、翻译盒子、设置页、复制文本）
 - [x] #35 将网页翻译功能移动到翻译盒子里去
 - [x] #68 网页划词翻译与翻译盒子的通用样式
 - [x] 设置页中添加/删除禁用域名功能的样式
 - [x] 添加 v5.x 中的谷歌翻译与必应翻译，见 [translation.js](https://github.com/lmk123/translation.js)
 - [x] 错误处理
 - [x] 完善朗读功能
 - [x] 对比 v5.6.1 与 v6.0 看看有哪些遗漏的细节
 - [x] #71 发布 Beta 版至 Chrome 网上应用店并小范围的测试
 - [x] 全面重构代码便于写单元测试
 - [x] 最后，完成接近 100% 的测试覆盖率

功能基本已开发完成，我已经将 v6.0 Beta 版发布至 Chrome 网上应用店了，你可以[帮忙测试](https://github.com/lmk123/crx-selection-translate/issues/71)。

**Comment by lmk123** [comment]
在 v6.0 重构过程中，我考虑将查询翻译结果的逻辑放到内容脚本，但是看到了 #3 之后犹豫了。不过我测试了一下（Chrome v45），在 github 的内容脚本里访问 http 的资源确实会有一个警告，但是结果还是能获取的。以防万一我还是仍然把查询逻辑放在 background 好了。

**Comment by lmk123** [comment]
重构完成。
